"""Configuration: schema, layered loading, and validation.

One ``config.json`` at the repo root holds every knob. It is generated by the
first-run wizard (:mod:`controller_validation_task.gui`) and gitignored, so
each rig keeps its own ports and display setup.

Precedence — **later wins**::

    defaults (the dataclasses below)
      < config.json
        < environment variables / .env
          < CLI flags

Design notes worth keeping:

* Every section is a ``frozen`` dataclass, so settings cannot be mutated
  halfway through a run; overrides are applied with :func:`dataclasses.replace`.
* Unknown JSON keys are dropped with an INFO log rather than raising, so a
  config written by a newer version still loads (forward compatibility).
* Missing keys fall back to the dataclass default, so a hand-written partial
  config works.
* :func:`_validate` raises ``ValueError`` with a message that explains *why*
  the constraint exists and what to change — these are read by an operator
  setting up a rig, not by a developer.

Pure module: stdlib + the marker code dataclass. No psychopy import.
"""

from __future__ import annotations

import dataclasses
import json
import logging
import os
from collections.abc import Callable, Mapping
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Any, Literal

from controller_validation_task.design import DEFAULT_CONDITIONS, DEFAULT_KEYS
from controller_validation_task.markers import TriggerCodes

log = logging.getLogger(__name__)

#: Bumped only on a breaking change. A mismatch is a hard error telling the
#: operator to delete config.json and re-run the wizard — there is no
#: migration path, deliberately.
SCHEMA_VERSION = 1

TriggerBackend = Literal["lsl", "serial", "parallel", "null"]
SyncMode = Literal["send", "wait", "none"]
SyncBackend = Literal["none", "serial", "parallel", "lsl", "key", "keyboard", "markers"]

#: Sync backends that physically write to a port and therefore need one.
_PORT_BACKENDS = ("serial", "parallel")


# ---------------------------------------------------------------------------
# Sections
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class DisplaySettings:
    """Window geometry and the two display-derived timing constants.

    Attributes:
        fullscreen:           Open fullscreen. Also drives ``allowGUI``.
        screen_index:         Monitor to open on; ``None`` auto-detects.
        window_size:          ``[w, h]``; ``None`` uses the screen geometry.
        frame_rate:           Assumed refresh in Hz. Each flip is scheduled one
                              frame early (``onset - 1/frame_rate``), so this
                              must match the real monitor or every trial lands
                              a fraction late.
        instruction_duration: Seconds each instruction screen is shown.
    """

    fullscreen: bool = True
    screen_index: int | None = None
    window_size: tuple[int, int] | None = None
    frame_rate: float = 60.0
    instruction_duration: float = 3.0


@dataclass(frozen=True)
class PathSettings:
    """Where outputs go and where the controller assets come from.

    ``assets_dir`` / ``layout_file`` are both ``None`` by default, meaning
    "use the controller shipped with the package".
    """

    output_root: str = "output"
    assets_dir: str | None = None
    layout_file: str | None = None


@dataclass(frozen=True)
class DesignSettings:
    """Trial structure and timing. See :mod:`controller_validation_task.design`.

    The defaults reproduce the original ``task_stimuli`` task: 8 buttons,
    5 short + 5 long blocks, 80 trials per run, 2 runs, TR-locked jitter.
    """

    keys: tuple[str, ...] = DEFAULT_KEYS
    conditions: tuple[str, ...] = DEFAULT_CONDITIONS
    n_runs: int = 2
    n_blocks_per_condition: int = 5
    short_press_duration: float = 0.3
    long_duration_range: tuple[float, float] = (1.0, 3.0)
    # `tr` is not used for timing or synchronisation — nothing is locked to
    # the scanner clock. It exists only as the scale for the inter-stimulus
    # jitter: leaving `isi_range` and `block_isi` null derives them as
    # (TR, 2*TR) and 2*TR, so gaps between presses land on a spread of
    # TR phases and the HRF gets sampled evenly. Set both explicitly (in
    # seconds) and `tr` stops mattering entirely.
    tr: float = 1.49
    isi_range: tuple[float, float] | None = None
    block_isi: float | None = None
    initial_wait: float = 3.0
    final_wait: float = 9.0
    response_window: float = 1.0
    lr_mode: bool = False
    seed: int | None = None


#: Default keyboard -> button mapping.
#:
#: Two families of key name are accepted out of the box, because
#: fMRI-compatible pads reach the computer in two different ways:
#:
#: * **Arrow keys** (``left``/``right``/``up``/``down``) — what most pads and
#:   the raw HID-to-keyboard adapters emit for the D-pad.
#: * **Letters** (``l``/``r``/``u``/``d``) — what the bundled AntiMicroX
#:   profile emits.
#:
#: Face buttons are ``a``/``b``/``x``/``y`` either way. Mapping both families
#: onto the same four D-pad buttons means either controller works with no
#: configuration; override ``input.key_map`` for anything else.
DEFAULT_KEY_MAP: dict[str, str] = {
    # Arrow keys (pyglet symbol names, lowercased)
    "left": "l",
    "right": "r",
    "up": "u",
    "down": "d",
    # AntiMicroX letter profile
    "l": "l",
    "r": "r",
    "u": "u",
    "d": "d",
    # Face buttons
    "a": "a",
    "b": "b",
    "x": "x",
    "y": "y",
}


@dataclass(frozen=True)
class InputSettings:
    """How keystrokes from the controller map onto controller buttons.

    The task reads the pad as a keyboard. ``key_map`` translates the key name
    PsychoPy reports into the button name used by ``design.keys`` and the
    controller layout, so the same task works whether the pad sends arrow keys
    or letters.

    Several keys may map to the same button (that is how both families above
    coexist). A key that is not in the map is still recorded in
    ``all_keypresses`` — it just never counts as the cued response.
    """

    key_map: dict[str, str] = field(default_factory=lambda: dict(DEFAULT_KEY_MAP))


@dataclass(frozen=True)
class SyncSettings:
    """How the run start is aligned with the recording device.

    ``mode`` says *what happens* at run start:
      * ``"none"`` — start immediately. The default.
      * ``"wait"`` — block until the sync signal arrives.
      * ``"send"`` — emit ``signal`` once, to start the recording device.
        This is the fMRI case where the stimulus computer starts the scanner.

    ``backend`` says *over what*, and defaults to ``"none"`` — no hardware:
      * in ``wait`` mode the signal is then expected from the **keyboard**
        (most MR trigger boxes present as a USB keyboard emitting ``5`` or
        ``t``, so this is also the usual scanner setup);
      * in ``send`` mode there is nothing to send to, so the run starts
        immediately with a warning.

    Otherwise: ``serial`` / ``parallel`` write or read a byte on ``port``,
    ``lsl`` and ``key`` send only, ``keyboard`` waits only, and ``markers``
    (send only) re-uses the already-open outgoing marker backend so a single
    serial port can carry both the start signal and the event markers without
    being opened twice.

    ``signal`` is the sync signal itself, and means the same thing in both
    directions: in ``send`` mode it is what goes out (``"s"`` -> the byte 115),
    in ``wait`` mode it is what we listen for. It may list alternatives, which
    is what a keyboard trigger box usually needs — ``["5", "percent"]`` are the
    same physical key with and without shift. Only the first entry is ever
    sent.

    A ``serial``/``parallel`` port that is unset or will not open degrades to
    the ``"none"`` behaviour above rather than aborting the session.
    """

    mode: SyncMode = "none"
    backend: SyncBackend = "none"
    port: str | None = None
    signal: tuple[str, ...] = ("s",)
    n_dummy_scans: int = 0
    timeout_seconds: float | None = None


@dataclass(frozen=True)
class TriggerSettings:
    """Outgoing event markers for MEG / EEG.

    Independent of :class:`SyncSettings`: a run can wait for a scanner and
    also emit markers, or do neither.
    """

    backend: TriggerBackend = "null"
    port: str | None = None
    lsl_stream_name: str = "controller_validation"
    lsl_stream_type: str = "Markers"
    lsl_stream_source_id: str = "controller_validation_markers"
    codes: TriggerCodes = field(default_factory=TriggerCodes)
    on_trial_onset: bool = True
    on_trial_offset: bool = True
    on_keypress: bool = False


@dataclass(frozen=True)
class Settings:
    """The whole configuration."""

    schema_version: int = SCHEMA_VERSION
    display: DisplaySettings = field(default_factory=DisplaySettings)
    paths: PathSettings = field(default_factory=PathSettings)
    design: DesignSettings = field(default_factory=DesignSettings)
    input: InputSettings = field(default_factory=InputSettings)
    sync: SyncSettings = field(default_factory=SyncSettings)
    triggers: TriggerSettings = field(default_factory=TriggerSettings)


def default_settings() -> Settings:
    """A fresh :class:`Settings` with every default in place."""
    return Settings()


def config_path_default() -> Path:
    """Default config location: ``./config.json`` relative to the cwd."""
    return Path("config.json")


# ---------------------------------------------------------------------------
# Serialization
# ---------------------------------------------------------------------------


def _filter_known(data: Mapping[str, Any], cls: type) -> dict[str, Any]:
    """Drop keys ``cls`` does not declare, logging once at INFO.

    Forward compatibility: a config.json written by a newer version (or one
    with a stray ``_comment``) still loads instead of raising.
    """
    known = {f.name for f in dataclasses.fields(cls)}
    unknown = [k for k in data if k not in known]
    if unknown:
        log.info("Ignoring unknown %s keys in config.json: %s", cls.__name__, unknown)
    return {k: v for k, v in data.items() if k in known}


def _tuple_or_none(value: Any) -> tuple | None:
    return None if value is None else tuple(value)


def _str_tuple(value: Any) -> tuple[str, ...]:
    """Accept ``"s"`` as readily as ``["5", "percent"]``.

    A single key is the common case, and quoting it as a bare string is what
    anyone hand-editing config.json will do.

    >>> _str_tuple("s")
    ('s',)
    >>> _str_tuple(["5", "percent"])
    ('5', 'percent')
    """
    return (value,) if isinstance(value, str) else tuple(str(v) for v in value)


#: Per-section coercions applied after JSON load, so lists become the tuples
#: the frozen dataclasses declare (JSON has no tuple type).
_COERCE: dict[str, dict[str, Callable[[Any], Any]]] = {
    "display": {"window_size": _tuple_or_none},
    "design": {
        "keys": tuple,
        "conditions": tuple,
        "long_duration_range": tuple,
        "isi_range": _tuple_or_none,
    },
    "sync": {"signal": _str_tuple},
}


def _section_from_dict(data: Mapping[str, Any], cls: type, name: str):
    kwargs = _filter_known(data, cls)
    for key, fn in _COERCE.get(name, {}).items():
        if key in kwargs:
            kwargs[key] = fn(kwargs[key])
    return cls(**kwargs)


def from_dict(data: Mapping[str, Any]) -> Settings:
    """Build :class:`Settings` from a parsed config dict (defaults for gaps)."""
    version = data.get("schema_version", SCHEMA_VERSION)
    if version != SCHEMA_VERSION:
        raise ValueError(
            f"config.json has schema_version {version}, but this version of "
            f"controller_validation_task expects {SCHEMA_VERSION}. There is no "
            f"migration path by design: delete config.json and re-run the task "
            f"to regenerate it with the wizard."
        )

    triggers_data = dict(data.get("triggers") or {})
    codes_data = triggers_data.pop("codes", None)
    triggers = _section_from_dict(triggers_data, TriggerSettings, "triggers")
    if codes_data:
        triggers = replace(
            triggers, codes=TriggerCodes(**_filter_known(codes_data, TriggerCodes))
        )

    return Settings(
        schema_version=SCHEMA_VERSION,
        display=_section_from_dict(data.get("display") or {}, DisplaySettings, "display"),
        paths=_section_from_dict(data.get("paths") or {}, PathSettings, "paths"),
        design=_section_from_dict(data.get("design") or {}, DesignSettings, "design"),
        input=_section_from_dict(data.get("input") or {}, InputSettings, "input"),
        sync=_section_from_dict(data.get("sync") or {}, SyncSettings, "sync"),
        triggers=triggers,
    )


def to_dict(settings: Settings) -> dict[str, Any]:
    """Serialize to a JSON-ready dict (tuples become lists)."""

    def _plain(value: Any) -> Any:
        if isinstance(value, tuple):
            return list(value)
        if isinstance(value, Path):
            return str(value)
        return value

    out: dict[str, Any] = {"schema_version": settings.schema_version}
    for section in ("display", "paths", "design", "input", "sync", "triggers"):
        obj = getattr(settings, section)
        out[section] = {
            f.name: (
                dataclasses.asdict(getattr(obj, f.name))
                if dataclasses.is_dataclass(getattr(obj, f.name))
                else _plain(getattr(obj, f.name))
            )
            for f in dataclasses.fields(obj)
        }
    return out


def load_from_file(config_path: str | os.PathLike[str]) -> Settings:
    """Read and parse a config.json (no env / CLI layering, no validation)."""
    raw = json.loads(Path(config_path).read_text(encoding="utf-8"))
    return from_dict(raw)


def save(settings: Settings, config_path: str | os.PathLike[str]) -> Path:
    """Validate then atomically write ``settings`` to ``config_path``."""
    _validate(settings)
    p = Path(config_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_suffix(p.suffix + ".tmp")
    tmp.write_text(json.dumps(to_dict(settings), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    os.replace(tmp, p)
    return p


# ---------------------------------------------------------------------------
# Environment + CLI layers
# ---------------------------------------------------------------------------


def _parse_bool(val: str) -> bool:
    return val.strip().lower() not in ("0", "false", "no", "off", "")


def _parse_opt_int(val: str) -> int | None:
    return None if val.strip() == "" else int(val)


def _parse_keys(val: str) -> tuple[str, ...]:
    """Comma-separated key names, for the one-line-per-setting env format.

    >>> _parse_keys("s")
    ('s',)
    >>> _parse_keys("5, percent")
    ('5', 'percent')
    """
    return tuple(part.strip() for part in val.split(",") if part.strip())


#: env var -> (section, field, parser). Declarative so the .env.example file
#: and this table can be checked against each other by eye.
_ENV_KEYS: dict[str, tuple[str, str, Any]] = {
    "CVT_OUTPUT_ROOT": ("paths", "output_root", str),
    "CVT_ASSETS_DIR": ("paths", "assets_dir", str),
    "CVT_LAYOUT_FILE": ("paths", "layout_file", str),
    "CVT_N_RUNS": ("design", "n_runs", int),
    "CVT_LR_MODE": ("design", "lr_mode", "bool"),
    "CVT_TR": ("design", "tr", float),
    "CVT_SEED": ("design", "seed", "opt_int"),
    "CVT_SYNC_MODE": ("sync", "mode", str),
    "CVT_SYNC_BACKEND": ("sync", "backend", str),
    "CVT_SYNC_PORT": ("sync", "port", str),
    "CVT_SYNC_SIGNAL": ("sync", "signal", "keys"),
    "CVT_TRIGGER_BACKEND": ("triggers", "backend", str),
    "CVT_TRIGGER_PORT": ("triggers", "port", str),
    "LSL_STREAM_NAME": ("triggers", "lsl_stream_name", str),
    "LSL_STREAM_TYPE": ("triggers", "lsl_stream_type", str),
    "LSL_STREAM_SOURCE_ID": ("triggers", "lsl_stream_source_id", str),
    "EXP_WIN_FULLSCR": ("display", "fullscreen", "bool"),
    "EXP_WIN_SCREEN": ("display", "screen_index", int),
}

_PARSERS: dict[Any, Callable[[str], Any]] = {
    "bool": _parse_bool,
    "opt_int": _parse_opt_int,
    "keys": _parse_keys,
}


def _apply_env(settings: Settings, env: Mapping[str, str]) -> Settings:
    patches: dict[str, dict[str, Any]] = {}
    for var, (section, fieldname, kind) in _ENV_KEYS.items():
        if var not in env:
            continue
        parser = _PARSERS.get(kind, kind)
        try:
            patches.setdefault(section, {})[fieldname] = parser(env[var])
        except (TypeError, ValueError) as exc:
            raise ValueError(f"Cannot parse environment variable {var}={env[var]!r}: {exc}") from exc

    # EXP_WIN_W / EXP_WIN_H compose one field, so they don't fit the table.
    if "EXP_WIN_W" in env and "EXP_WIN_H" in env:
        patches.setdefault("display", {})["window_size"] = (
            int(env["EXP_WIN_W"]),
            int(env["EXP_WIN_H"]),
        )

    return _apply_patches(settings, patches)


#: CLI dest -> (section, field). Values of ``None`` mean "flag not given".
_CLI_KEYS: dict[str, tuple[str, str]] = {
    "output_root": ("paths", "output_root"),
    "layout_file": ("paths", "layout_file"),
    "n_runs": ("design", "n_runs"),
    "lr_mode": ("design", "lr_mode"),
    "fullscreen": ("display", "fullscreen"),
    "screen_index": ("display", "screen_index"),
    "window_size": ("display", "window_size"),
    "instruction_duration": ("display", "instruction_duration"),
    "sync_mode": ("sync", "mode"),
    "sync_backend": ("sync", "backend"),
    "sync_port": ("sync", "port"),
    "sync_signal": ("sync", "signal"),
    "trigger_backend": ("triggers", "backend"),
    "trigger_port": ("triggers", "port"),
}


def _apply_cli(settings: Settings, overrides: Mapping[str, Any]) -> Settings:
    patches: dict[str, dict[str, Any]] = {}
    for name, value in overrides.items():
        if value is None or name not in _CLI_KEYS:
            continue
        section, fieldname = _CLI_KEYS[name]
        patches.setdefault(section, {})[fieldname] = value
    return _apply_patches(settings, patches)


def _apply_patches(settings: Settings, patches: Mapping[str, dict[str, Any]]) -> Settings:
    if not patches:
        return settings
    sections = {
        name: replace(getattr(settings, name), **patch) for name, patch in patches.items()
    }
    return replace(settings, **sections)


def load(
    config_path: str | os.PathLike[str] | None = None,
    env: Mapping[str, str] | None = None,
    cli_overrides: Mapping[str, Any] | None = None,
) -> Settings:
    """Build the effective settings from every layer, then validate.

    Args:
        config_path:   config.json to read; skipped silently if it is missing,
                       so a fresh checkout runs on defaults.
        env:           Environment mapping; defaults to ``os.environ``.
        cli_overrides: ``{dest: value}`` from argparse. ``None`` values mean
                       "flag not supplied" and are ignored.

    Raises:
        ValueError: the merged configuration is invalid (see :func:`_validate`).
    """
    settings = default_settings()
    if config_path is not None and Path(config_path).exists():
        settings = load_from_file(config_path)
    settings = _apply_env(settings, os.environ if env is None else env)
    if cli_overrides:
        settings = _apply_cli(settings, cli_overrides)
    _validate(settings)
    return settings


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def _validate(s: Settings) -> None:
    """Raise ``ValueError`` if the configuration cannot produce a valid run."""
    _validate_design(s.design)
    _validate_display(s.display)
    _validate_input(s.input, s.design)
    _validate_sync(s.sync)
    _validate_triggers(s.triggers, s.design)


def _validate_design(d: DesignSettings) -> None:
    if not d.keys:
        raise ValueError("design.keys is empty: there would be no button to cue.")
    if len(set(d.keys)) != len(d.keys):
        raise ValueError(f"design.keys contains duplicates: {d.keys}.")
    if not d.conditions:
        raise ValueError("design.conditions is empty: there would be no trials.")
    if len(set(d.conditions)) != len(d.conditions):
        raise ValueError(f"design.conditions contains duplicates: {d.conditions}.")
    if d.n_runs < 1:
        raise ValueError(f"design.n_runs must be >= 1, got {d.n_runs}.")
    if d.n_blocks_per_condition < 1:
        raise ValueError(
            f"design.n_blocks_per_condition must be >= 1, got {d.n_blocks_per_condition}."
        )
    if d.short_press_duration <= 0:
        raise ValueError(
            f"design.short_press_duration must be > 0, got {d.short_press_duration}."
        )
    lo, hi = d.long_duration_range
    if not (0 < lo <= hi):
        raise ValueError(
            f"design.long_duration_range must be [low, high] with 0 < low <= high, "
            f"got {d.long_duration_range}."
        )
    if d.tr <= 0:
        raise ValueError(f"design.tr must be > 0, got {d.tr} (it seeds the ISI defaults).")
    if d.isi_range is not None:
        ilo, ihi = d.isi_range
        if not (0 < ilo <= ihi):
            raise ValueError(
                f"design.isi_range must be [low, high] with 0 < low <= high, "
                f"got {d.isi_range}. Set it to null to derive [TR, 2*TR]."
            )
    if d.block_isi is not None and d.block_isi < 0:
        raise ValueError(f"design.block_isi must be >= 0, got {d.block_isi}.")
    if d.initial_wait < 0 or d.final_wait < 0:
        raise ValueError("design.initial_wait and design.final_wait must be >= 0.")
    if d.response_window <= 0:
        raise ValueError(
            f"design.response_window must be > 0, got {d.response_window}. It is the "
            f"grace period after a trial's offset during which a late release is "
            f"still attributed to that trial."
        )


def _validate_input(i: InputSettings, d: DesignSettings) -> None:
    if not i.key_map:
        raise ValueError(
            "input.key_map is empty, so no keypress could ever be matched to a "
            "cued button. Restore the default map or list your controller's keys."
        )

    # Entries pointing at buttons this design does not cue are harmless — the
    # default map covers the whole pad, and narrowing design.keys for a pilot
    # is a normal thing to do — so this is a warning, not an error.
    unknown = sorted({v for v in i.key_map.values() if v not in d.keys})
    if unknown:
        log.info(
            "input.key_map maps keys onto %s, which design.keys does not cue; "
            "those entries will simply never match.",
            unknown,
        )

    # The more dangerous direction: a button that is cued but that no key can
    # ever produce. The run would look fine and record no responses for it.
    unreachable = [k for k in d.keys if k not in set(i.key_map.values())]
    if unreachable:
        raise ValueError(
            f"design.keys includes {unreachable}, which no entry of input.key_map "
            f"produces, so those trials could never be answered. Add the key(s) "
            f"your controller sends for them, e.g. {{\"left\": \"{unreachable[0]}\"}}."
        )


def _validate_display(d: DisplaySettings) -> None:
    if d.frame_rate <= 0:
        raise ValueError(
            f"display.frame_rate must be > 0, got {d.frame_rate}. Each flip is "
            f"scheduled one frame early, so this must match the real refresh rate."
        )
    if d.instruction_duration < 0:
        raise ValueError("display.instruction_duration must be >= 0.")
    if d.window_size is not None and (
        len(d.window_size) != 2 or any(v <= 0 for v in d.window_size)
    ):
        raise ValueError(
            f"display.window_size must be [width, height] with positive values, "
            f"got {d.window_size}. Set it to null to use the screen geometry."
        )
    if d.screen_index is not None and d.screen_index < 0:
        raise ValueError("display.screen_index must be >= 0, or null to auto-detect.")


def _validate_sync(s: SyncSettings) -> None:
    valid_modes = ("send", "wait", "none")
    if s.mode not in valid_modes:
        raise ValueError(f"sync.mode must be one of {valid_modes}, got {s.mode!r}.")

    if s.mode != "none" and not s.signal:
        raise ValueError(
            "sync.signal is empty: there would be nothing to send, and nothing "
            "a scanner TTL could match. Most MR trigger boxes emit '5' or 't'."
        )

    if s.mode == "send":
        valid = ("none", "serial", "parallel", "lsl", "key", "markers")
        if s.backend not in valid:
            raise ValueError(
                f"sync.backend for mode 'send' must be one of {valid}, got {s.backend!r}."
            )
        # A missing port is deliberately NOT an error: sync.configure() warns
        # and starts the run anyway, so the same config works at the scanner
        # and on a desk.

    if s.mode == "wait":
        valid = ("none", "keyboard", "serial")
        if s.backend not in valid:
            raise ValueError(
                f"sync.backend for mode 'wait' must be one of {valid}, got {s.backend!r}."
            )
        # As above: no port means fall back to the keyboard, not refuse to run.

    if s.n_dummy_scans < 0:
        raise ValueError(f"sync.n_dummy_scans must be >= 0, got {s.n_dummy_scans}.")
    if s.timeout_seconds is not None and s.timeout_seconds <= 0:
        raise ValueError(
            f"sync.timeout_seconds must be > 0, got {s.timeout_seconds}. "
            f"Set it to null to wait indefinitely."
        )


def _validate_triggers(t: TriggerSettings, d: DesignSettings) -> None:
    valid = ("lsl", "serial", "parallel", "null")
    if t.backend not in valid:
        raise ValueError(f"triggers.backend must be one of {valid}, got {t.backend!r}.")
    if t.backend in _PORT_BACKENDS and not t.port:
        raise ValueError(
            f"triggers.backend is {t.backend!r} but triggers.port is not set, e.g. "
            f"'/dev/ttyACM0' (serial) or '/dev/parport1' (parallel)."
        )

    c = t.codes
    named = {
        "task_start": c.task_start,
        "task_stop": c.task_stop,
        "trial_onset_short": c.trial_onset_short,
        "trial_onset_long": c.trial_onset_long,
        "trial_offset": c.trial_offset,
    }
    # 1. Every marker must fit in the single byte serial/parallel can carry.
    for name, value in {**named, "key_base": c.key_base}.items():
        if not (0 <= value <= 255):
            raise ValueError(
                f"triggers.codes.{name} must be 0..255 (markers are sent as one "
                f"byte on serial/parallel), got {value}."
            )
    # 2. Lifecycle codes must be distinguishable from each other.
    dupes = {v for v in named.values() if list(named.values()).count(v) > 1}
    if dupes:
        raise ValueError(
            f"triggers.codes has duplicate values {sorted(dupes)} among "
            f"{sorted(named)}; each event type needs its own code to be decodable."
        )
    # 3. Per-key codes occupy key_base .. key_base+len(keys)-1 and must not
    #    collide with the lifecycle codes or run off the end of the byte.
    key_span = range(c.key_base, c.key_base + len(d.keys))
    if key_span.stop > 256:
        raise ValueError(
            f"triggers.codes.key_base={c.key_base} plus {len(d.keys)} keys reaches "
            f"{key_span.stop - 1}, past the 255 a one-byte marker can hold. "
            f"Lower key_base or cue fewer buttons."
        )
    overlap = sorted(name for name, value in named.items() if value in key_span)
    if overlap:
        raise ValueError(
            f"triggers.codes.key_base={c.key_base} makes the per-key codes "
            f"{key_span.start}..{key_span.stop - 1} overlap the lifecycle code(s) "
            f"{overlap}. Move key_base above every lifecycle code."
        )
